version: '3.7'
services:
    application:
        container_name: design-customization-bundle_app
        image: richcongress/php:8.0
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
            - ~/.ssh:/home/application/.ssh:cached
